# Form implementation generated from reading ui file 'areaDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dispAxis = QtWidgets.QWidget(parent=self.centralwidget)
        self.dispAxis.setGeometry(QtCore.QRect(30, 10, 591, 611))
        self.dispAxis.setObjectName("dispAxis")
        self.signalAxis = QtWidgets.QWidget(parent=self.centralwidget)
        self.signalAxis.setGeometry(QtCore.QRect(640, 10, 331, 311))
        self.signalAxis.setObjectName("signalAxis")
        self.psAxis = QtWidgets.QWidget(parent=self.centralwidget)
        self.psAxis.setGeometry(QtCore.QRect(640, 330, 331, 311))
        self.psAxis.setObjectName("psAxis")
        self.slDisp = QtWidgets.QSlider(parent=self.centralwidget)
        self.slDisp.setGeometry(QtCore.QRect(50, 620, 501, 16))
        self.slDisp.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slDisp.setObjectName("slDisp")
        self.lbDisp = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbDisp.setGeometry(QtCore.QRect(560, 620, 61, 20))
        self.lbDisp.setObjectName("lbDisp")
        self.pbResetROI = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pbResetROI.setGeometry(QtCore.QRect(50, 640, 75, 23))
        self.pbResetROI.setObjectName("pbResetROI")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbDisp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">N/N</p></body></html>"))
        self.pbResetROI.setText(_translate("MainWindow", "Reset ROI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
