# Form implementation generated from reading ui file 'dialogWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(254, 152)
        self.lbIni = QtWidgets.QLabel(parent=Dialog)
        self.lbIni.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.lbIni.setObjectName("lbIni")
        self.lbEnd = QtWidgets.QLabel(parent=Dialog)
        self.lbEnd.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.lbEnd.setObjectName("lbEnd")
        self.sbIni = QtWidgets.QSpinBox(parent=Dialog)
        self.sbIni.setGeometry(QtCore.QRect(100, 20, 71, 22))
        self.sbIni.setObjectName("sbIni")
        self.sbEnd = QtWidgets.QSpinBox(parent=Dialog)
        self.sbEnd.setGeometry(QtCore.QRect(100, 50, 71, 22))
        self.sbEnd.setObjectName("sbEnd")
        self.pbOK = QtWidgets.QPushButton(parent=Dialog)
        self.pbOK.setGeometry(QtCore.QRect(30, 100, 75, 23))
        self.pbOK.setObjectName("pbOK")
        self.pbCancel = QtWidgets.QPushButton(parent=Dialog)
        self.pbCancel.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.pbCancel.setObjectName("pbCancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbIni.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Inital Frame:</p></body></html>"))
        self.lbEnd.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Final Frame:</p></body></html>"))
        self.pbOK.setText(_translate("Dialog", "OK"))
        self.pbCancel.setText(_translate("Dialog", "Cancel"))
